-- Moves Dues off Firestore now that a reference-number lookup and a
-- super-admin search panel are needed — this is the last table left on
-- Firebase. No real payment gateway (Monnify) is wired up yet, so `reference`
-- is generated by us as a lookup handle; when Monnify is integrated later,
-- its own transaction reference can be stored alongside this one.
create table public.dues_requests (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique default ('NAMSN-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8))),
  full_name text not null,
  email text not null,
  phone text not null,
  matric_number text not null,
  level text not null check (level in ('100', '200', '300', '400')),
  status text not null check (status in ('FRESHERS', 'STAYLITES')),
  amount integer not null,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);
alter table public.dues_requests enable row level security;

-- A student can submit their own request, and can only ever see requests
-- they personally submitted while logged in. Super admin can see and update
-- every request — that's the "search any payment receipt" panel.
create policy "dues_insert_own" on public.dues_requests
  for insert to authenticated with check (created_by = auth.uid());

create policy "dues_select_own_or_admin" on public.dues_requests
  for select using (created_by = auth.uid() or public.current_user_role() = 'super_admin');

create policy "dues_update_admin" on public.dues_requests
  for update using (public.current_user_role() = 'super_admin');
